# Makefile for building a generic userspace application
# Include all the definitions for os
APP_NAME := wintest
APP_SOURCES_CXX := main.cpp

INCLUDES := -I$(VALI_DDK_PATH)/include
LFLAGS := asgaard.lib libgracht.lib ddk.lib

include ../application.mk