name: Build i386 Nightly

on:
  schedule:
    # Nightly builds
    - cron: '0 12 * * *'
  workflow_dispatch:

jobs:
  check_date:
    runs-on: ubuntu-latest
    name: Check latest commit
    outputs:
      should_run: ${{ steps.should_run.outputs.should_run }}
    steps:
      - uses: actions/checkout@v2
      - name: print latest_commit
        run: echo ${{ github.sha }}

      - id: should_run
        continue-on-error: true
        name: check latest commit is less than a day
        if: ${{ github.event_name == 'schedule' }}
        run: test -z $(git rev-list  --after="24 hours"  ${{ github.sha }}) && echo "::set-output name=should_run::false"
  build:
    needs: check_date
    if: ${{ needs.check_date.outputs.should_run != 'false' }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Build and push
      uses: docker/build-push-action@v1.1.0
      with:
        build_args: ARCH=i386,THEME_SECRET=${{ secrets.VALI_THEME_CODE }}
    - uses: actions/upload-artifact@v2
      with:
        name: vali-apps-nightly-i386
        path: ./vali-apps.tar.gz
